### ISSUE TITLE
error for setUpBeforeClass()

### ISSUE THREAD

**Issue by Lechus** [elblinkin/PHPUnit-CodeSniffer#5]
Why:
Error: Found a public method that is not a test or a provider:
setUpBeforeClass

Example 6.2: Example showing all template methods available
http://www.phpunit.de/manual/current/en/fixtures.html#fixtures.more-setup-than-teardown
`public static function setUpBeforeClass()
    {
        fwrite(STDOUT, __METHOD__ . "\n");
    }`

**Comment by elblinkin** [comment]
It's possible to modify the rules to allow for the setUpBeforeClass() and tearDownAfterClass() methods, since they are indeed in the bse PHPUnit TestCase, but if you are using those methods, you should ask yourself if what you are testing is too complex to be a unit test or is it just unnecessarily expensive to setup.  Having class level test fixtures leads to interdependent tests.

As for this example, it should probably be not included like that in the PHPUnit documentation as there is a flag to provide that type of output without static function.
